version: "3.8"

services:
  rasa:
    build:
      context: .
      dockerfile: Dockerfile.rasa
    ports:
      - "5005:5005"
    networks:
      - bot-network

  flask:
    build:
      context: .
      dockerfile: Dockerfile.flask
    ports:
      - "8080:8080"
    environment:
      - RASA_SERVER_URL=http://rasa:5005/webhooks/rest/webhook
    networks:
      - bot-network

networks:
  bot-network:
    driver: bridge
