# Use Python base image
FROM python:3.9

# Install system dependencies
RUN apt-get update && apt-get install -y git && rm -rf /var/lib/apt/lists/*

# Set working directory
WORKDIR /app

# Install Flask and Requests
RUN pip install flask requests

# Copy Flask app and templates
COPY app.py . 
COPY templates/index.html templates/index.html

# Expose Flask port
EXPOSE 8080

# Start Flask app
CMD python app.py
